default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["PG_ADMIN_USERNAME"] %>
  password: <%= ENV["PG_ADMIN_PASSWORD"] %>

development:
  <<: *default
  #database: campus_dev
  database: yt_video_v3_dev

test:
  <<: *default
  database: yt_video_v3_test

production:
  <<: *default
  database: yt_video_v3_production
